language: cpp
sudo: false
dist: focal
os:
  - linux
  - osx
osx_image: xcode12.2
compiler:
  - clang
  - gcc
  
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - clang-9
      - libclang-9-dev
      - libclang-cpp9
      - libglu1-mesa-dev

stages:
  - name: build_documentation
  - name: build
  - name: test

jobs:
  exclude:
    - os: osx
      compiler: gcc
  include:
    - stage: build_documentation
      if: compiler=gcc
      if: os=linux
      script:
          - ./ci/travis_installdoxygen.sh
          - ./ci/travis_builddocumentation.sh

      deploy:
          provider: pages
          verbose: true
          deployment_file: true
          strategy: git
          skip_cleanup: true
          local_dir: doc/html
          github_token: $GH_REPO_TOKEN
          on:
            branch: master
            condition: $BUILD_DOXYGEN = yes    

    - stage: build
      script:
        - ./ci/travis_build.sh
    
    - stage: test
      script:
        - ./ci/travis_test.sh

install:
  - source ci/install_travis.sh

notifications:
  email: false

